# Generated by Django 6.0.3 on 2026-04-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at']},
        ),
    ]
